---
name: Bug report
about: Report a bug.
labels: 'bug'
---

<!-- Looking for Support 
Check out our support options at https://particular.net/support --> 

**Describe the bug**
A clear and concise description of what the bug is.

**How to reproduce**
Steps to reproduce the behavior:

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs**
If applicable, include a copy of any log messages that may help diagnose the bug.

**Versions of packages or applications used**
Please list the version of the relevant packages or applications in which the bug exists. 

**Additional context**
Add any other context about the problem here.
