---
name: Improvement request
about: Suggest an improvement
labels: 'Improvement'
---

<!-- Looking for Support 
Check out our support options at https://particular.net/support --> 

**Is your improvement request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or improvements you've considered.

**Additional context**
Add any other context or screenshots about the improvement request here.