name: NuGet Audit
on:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Linux
    runs-on: ubuntu-22.04    
    steps:
      - name: Check for secrets
        env:
          SECRETS_AVAILABLE: ${{ secrets.SECRETS_AVAILABLE }}
        shell: pwsh
        run: exit $(If ($env:SECRETS_AVAILABLE -eq 'true') { 0 } Else { 1 })
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.1.0
        with:
          global-json-file: global.json
      - name: Restore
        id: restore
        run:  echo CVECOUNT=$(dotnet restore src -v m | grep -c -e "NU190[1-4]") >> $GITHUB_OUTPUT
      - name: Upload
        if: steps.restore.outputs.CVECOUNT > 0
        run: |
          dotnet list package --vulnerable --include-transitive --format json >> "${{ github.workspace }}/vulnerabilities.json"
          jq -s '.' */obj/project.assets.json > "${{ github.workspace }}/all.project.assets.json"
          curl -F "vulnerabilities=${{ github.workspace }}/vulnerabilities.json" -F "assets=${{ github.workspace }}/all.project.assets.json" -H "x-functions-key: ${{ secrets.NUGET_AUDIT_TOKEN }}" ${{ secrets.INTERNAL_AUTOMATION_URI }}
          exit ${{ steps.restore.outputs.CVECOUNT }}